### PR TITLE
Small changes: New link, button, video

### PR DESCRIPTION
**Pull request by mathieuesteban**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @mathieuesteban,

The folder views/js is not used and can be safely removed.

**Comment by Quetzacoalt91** [comment]
Hi @mathieuesteban,

Just the version to update in the config.xml and we are good to go.

**Comment by mathieuesteban** [comment]
Hi @Quetzacoalt91,
The version number is updated.

**Comment by Quetzacoalt91** [comment]
Nope ! Wrong file ! :D

**Comment by mathieuesteban** [comment]
Hi @Quetzacoalt91,
Done

**Comment by Quetzacoalt91** [comment]
Thanks, the PR is now merged and the changes will be available soon.

**Pull request merged**
